### ISSUE TITLE
SyntaxFest2019.tex does not immediately work with XeLaTeX

### ISSUE THREAD

**Issue by adam-przepiorkowski** [syntaxfest/syntaxfest.github.io#2]
In order to xelatex SyntaxFest2019.tex I had to:

• comment out the following lines:

% \usepackage{luatexja-fontspec}
% \setmainjfont{FandolSong}

• put $ characters around ‘\times’ (in ‘(21 cm \times 29.7 cm)’)

**Comment by adam-przepiorkowski** [comment]
My comment concerns SyntaxFest2019.tex in SyntaxFestStyles.zip (linked from https://syntaxfest.github.io/syntaxfest19/).  I now see that the version in styles/LaTex/ differs from that in that ZIP archive.  But submitters will use the ZIP archive, following the link from SyntaxFest 2019 web pages.

**Comment by kimgerdes** [comment]
sorry about that error. it should be fixed now.
